build_script:
  - gradlew.bat --full-stacktrace clean build

test_script:
  - gradlew.bat --full-stacktrace check

cache:
  - .gradle
  - C:\Users\appveyor\.gradle

environment:
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
